version: 2
updates:
  # Configuration for Bun dependencies (package.json)
  - package-ecosystem: "npm" # Dependabot uses npm ecosystem for all package.json files, including Bun projects
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: auto
    labels:
      - "dependencies"
      - "bun"
    # Optional: Increase security by allowing security updates immediately
    # rather than waiting for scheduled time
    allow:
      - dependency-type: "all"