services:
  traefik:
    image: traefik:v3.4
    ports:
      - "71:71"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:71"
      - "--api.insecure=true"
      - "--metrics.prometheus=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.service=api@internal"

  web-dummy:
    image: ghcr.io/rstubryan/tascrum-web-dummy:latest
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BASE_URL=https://api.tascrum.site/api/v1
      - NEXT_PUBLIC_BASE_URL_BLOG=https://blog.sineasmov.com/wp-json/wp/v2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dummy.rule=PathPrefix(`/`)"
      - "traefik.http.routers.dummy.entrypoints=web"
      - "traefik.http.services.dummy.loadbalancer.server.port=3000"

  prometheus:
    image: prom/prometheus:latest
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=PathPrefix(`/prometheus`)"
      - "traefik.http.routers.prometheus.entrypoints=web"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.http.middlewares.prometheus-strip.stripprefix.prefixes=/prometheus"
      - "traefik.http.routers.prometheus.middlewares=prometheus-strip"

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=http://156.67.82.56:71/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - grafana-data:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=PathPrefix(`/grafana`)"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.grafana-strip.stripprefix.prefixes=/grafana"
      - "traefik.http.routers.grafana.middlewares=grafana-strip"

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blackbox.rule=PathPrefix(`/blackbox`)"
      - "traefik.http.routers.blackbox.entrypoints=web"
      - "traefik.http.services.blackbox.loadbalancer.server.port=9115"

volumes:
  prometheus-data:
  grafana-data: