services:
  haproxy:
    image: haproxy:latest
    ports:
      - "80:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - web

  web:
    image: ghcr.io/rstubryan/tascrum-web-dummy:latest
    environment:
      - NODE_ENV=production
    expose:
      - "3000"