services:
  server:
    build:
      context: .
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_BASE_URL=http://localhost:8000/api/v1
      - NEXT_PUBLIC_BASE_URL_BLOG=http://localhost:8000/api/v1/blog
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

networks:
  default:
    driver: bridge