services:
  traefik:
    image: "traefik:v3.4"
    command:
      - "--log.level=DEBUG"
      - "--api=true"
      - "--api.dashboard=true"
      - "--providers.swarm=true"
      - "--providers.swarm.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=restubumirr@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - mode: host
        published: 80
        target: 80
      - mode: host
        published: 443
        target: 443
      - mode: host
        published: 8080
        target: 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certificates:/letsencrypt
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        # Dashboard configuration
        - "traefik.http.routers.dashboard.rule=Host(`dashboard.tascrum.site`)"
        - "traefik.http.routers.dashboard.service=api@internal"
        - "traefik.http.routers.dashboard.entrypoints=websecure"
        - "traefik.http.routers.dashboard.tls.certresolver=myresolver"
        - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
        # HTTP to HTTPS redirect for dashboard
        - "traefik.http.routers.dashboard-http.rule=Host(`dashboard.tascrum.site`)"
        - "traefik.http.routers.dashboard-http.entrypoints=web"
        - "traefik.http.routers.dashboard-http.middlewares=dashboard-https-redirect"
        - "traefik.http.middlewares.dashboard-https-redirect.redirectscheme.scheme=https"

  web-prod:
    image: ghcr.io/rstubryan/tascrum-web-prod:latest
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BASE_URL=http://api-tascrum.zeabur.app/api/v1
      - NEXT_PUBLIC_BASE_URL_BLOG=http://api-tascrum.zeabur.app/api/v1/blog
    networks:
      - traefik-public
    deploy:
      replicas: 2
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.web-prod.rule=Host(`tascrum.site`)"
        - "traefik.http.routers.web-prod.entrypoints=websecure"
        - "traefik.http.routers.web-prod.tls.certresolver=myresolver"
        - "traefik.http.routers.web-prod-http.rule=Host(`tascrum.site`)"
        - "traefik.http.routers.web-prod-http.entrypoints=web"
        - "traefik.http.routers.web-prod-http.middlewares=web-prod-https-redirect"
        - "traefik.http.middlewares.web-prod-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.services.web-prod.loadbalancer.server.port=3000"

  web-dev:
    image: ghcr.io/rstubryan/tascrum-web:latest
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_BASE_URL=http://api-tascrum.zeabur.app/api/v1
      - NEXT_PUBLIC_BASE_URL_BLOG=http://api-tascrum.zeabur.app/api/v1/blog
    networks:
      - traefik-public
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.web-dev.rule=Host(`dev.tascrum.site`)"
        - "traefik.http.routers.web-dev.entrypoints=websecure"
        - "traefik.http.routers.web-dev.tls.certresolver=myresolver"
        - "traefik.http.routers.web-dev-http.rule=Host(`dev.tascrum.site`)"
        - "traefik.http.routers.web-dev-http.entrypoints=web"
        - "traefik.http.routers.web-dev-http.middlewares=web-dev-https-redirect"
        - "traefik.http.middlewares.web-dev-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.services.web-dev.loadbalancer.server.port=3000"

networks:
  traefik-public:
    driver: overlay
    attachable: true

volumes:
  traefik-certificates: