services:
  traefik:
    image: "traefik:v3.4"
    command:
      - "--log.level=DEBUG"
      - "--api=true"
      - "--api.dashboard=true"
      - "--providers.swarm=true"
      - "--providers.swarm.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=restubumirr@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - mode: host
        published: 80
        target: 80
      - mode: host
        published: 443
        target: 443
      - mode: host
        published: 8080
        target: 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certificates:/letsencrypt
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        # Dashboard configuration
        - "traefik.http.routers.dashboard.rule=Host(`dashboard.tascrum.site`)"
        - "traefik.http.routers.dashboard.service=api@internal"
        - "traefik.http.routers.dashboard.entrypoints=websecure"
        - "traefik.http.routers.dashboard.tls.certresolver=myresolver"
        - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
        # HTTP to HTTPS redirect for dashboard
        - "traefik.http.routers.dashboard-http.rule=Host(`dashboard.tascrum.site`)"
        - "traefik.http.routers.dashboard-http.entrypoints=web"
        - "traefik.http.routers.dashboard-http.middlewares=dashboard-https-redirect"
        - "traefik.http.middlewares.dashboard-https-redirect.redirectscheme.scheme=https"

  loki:
    image: grafana/loki:2.9.1
    command: -config.file=/etc/loki/local-config.yaml
    configs:
      - source: loki-config
        target: /etc/loki/local-config.yaml
    volumes:
      - loki-data:/loki
    networks:
      - traefik-public
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.loki.rule=Host(`loki.tascrum.site`)"
        - "traefik.http.routers.loki.entrypoints=websecure"
        - "traefik.http.routers.loki.tls.certresolver=myresolver"
        - "traefik.http.services.loki.loadbalancer.server.port=3100"

  promtail:
    image: grafana/promtail:2.9.1
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - promtail-data:/tmp
    configs:
      - source: promtail-config
        target: /etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - traefik-public
    deploy:
      mode: global

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secure_password
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=https://monitor.tascrum.site
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-clock-panel
    volumes:
      - grafana-data:/var/lib/grafana
    configs:
      - source: grafana-datasources
        target: /etc/grafana/provisioning/datasources/datasources.yaml
      - source: grafana-dashboards-config
        target: /etc/grafana/provisioning/dashboards/dashboards.yaml
    networks:
      - traefik-public
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.grafana.rule=Host(`monitor.tascrum.site`)"
        - "traefik.http.routers.grafana.entrypoints=websecure"
        - "traefik.http.routers.grafana.tls.certresolver=myresolver"
        - "traefik.http.routers.grafana-http.rule=Host(`monitor.tascrum.site`)"
        - "traefik.http.routers.grafana-http.entrypoints=web"
        - "traefik.http.routers.grafana-http.middlewares=grafana-https-redirect"
        - "traefik.http.middlewares.grafana-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"

  web-prod:
    image: ghcr.io/rstubryan/tascrum-web-prod:latest
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BASE_URL=http://api-tascrum.zeabur.app/api/v1
      - NEXT_PUBLIC_BASE_URL_BLOG=http://api-tascrum.zeabur.app/api/v1/blog
    networks:
      - traefik-public
    deploy:
      replicas: 2
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.web-prod.rule=Host(`tascrum.site`)"
        - "traefik.http.routers.web-prod.entrypoints=websecure"
        - "traefik.http.routers.web-prod.tls.certresolver=myresolver"
        - "traefik.http.routers.web-prod-http.rule=Host(`tascrum.site`)"
        - "traefik.http.routers.web-prod-http.entrypoints=web"
        - "traefik.http.routers.web-prod-http.middlewares=web-prod-https-redirect"
        - "traefik.http.middlewares.web-prod-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.services.web-prod.loadbalancer.server.port=3000"

  web-dev:
    image: ghcr.io/rstubryan/tascrum-web:latest
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_BASE_URL=http://api-tascrum.zeabur.app/api/v1
      - NEXT_PUBLIC_BASE_URL_BLOG=http://api-tascrum.zeabur.app/api/v1/blog
    networks:
      - traefik-public
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.web-dev.rule=Host(`dev.tascrum.site`)"
        - "traefik.http.routers.web-dev.entrypoints=websecure"
        - "traefik.http.routers.web-dev.tls.certresolver=myresolver"
        - "traefik.http.routers.web-dev-http.rule=Host(`dev.tascrum.site`)"
        - "traefik.http.routers.web-dev-http.entrypoints=web"
        - "traefik.http.routers.web-dev-http.middlewares=web-dev-https-redirect"
        - "traefik.http.middlewares.web-dev-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.services.web-dev.loadbalancer.server.port=3000"

configs:
  loki-config:
    file: ./configs/loki-config.yaml
  promtail-config:
    file: ./configs/promtail-config.yaml
  grafana-datasources:
    file: ./configs/grafana-datasources.yaml
  grafana-dashboards-config:
    file: ./configs/grafana-dashboards-config.yaml

networks:
  traefik-public:
    driver: overlay
    attachable: true

volumes:
  traefik-certificates:
  grafana-data:
  loki-data:
  promtail-data: