services:
  traefik:
    image: "traefik:v3.4"
    command:
      - "--log.level=DEBUG"
      - "--api=true"
      - "--api.dashboard=true"
      - "--providers.swarm=true"
      - "--providers.swarm.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=restubumirr@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - mode: host
        published: 80
        target: 80
      - mode: host
        published: 443
        target: 443
      - mode: host
        published: 8080
        target: 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certificates:/letsencrypt
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        # Dashboard configuration
        - "traefik.http.routers.dashboard.rule=Host(`dashboard.tascrum.site`)"
        - "traefik.http.routers.dashboard.service=api@internal"
        - "traefik.http.routers.dashboard.entrypoints=websecure"
        - "traefik.http.routers.dashboard.tls.certresolver=myresolver"
        - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
        # HTTP to HTTPS redirect for dashboard
        - "traefik.http.routers.dashboard-http.rule=Host(`dashboard.tascrum.site`)"
        - "traefik.http.routers.dashboard-http.entrypoints=web"
        - "traefik.http.routers.dashboard-http.middlewares=dashboard-https-redirect"
        - "traefik.http.middlewares.dashboard-https-redirect.redirectscheme.scheme=https"

  loki:
    image: grafana/loki:2.9.1
    command: -config.file=/etc/loki/local-config.yaml
    configs:
      - source: loki-config
        target: /etc/loki/local-config.yaml
    volumes:
      - loki-data:/loki
    networks:
      - traefik-public
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.loki.rule=Host(`loki.tascrum.site`)"
        - "traefik.http.routers.loki.entrypoints=websecure"
        - "traefik.http.routers.loki.tls.certresolver=myresolver"
        - "traefik.http.services.loki.loadbalancer.server.port=3100"

  promtail:
    image: grafana/promtail:2.9.1
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - promtail-data:/tmp
    configs:
      - source: promtail-config
        target: /etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - traefik-public
    deploy:
      mode: global

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secure_password
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=https://monitor.tascrum.site
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-clock-panel
    volumes:
      - grafana-data:/var/lib/grafana
    configs:
      - source: grafana-datasources
        target: /etc/grafana/provisioning/datasources/datasources.yaml
      - source: grafana-dashboards-config
        target: /etc/grafana/provisioning/dashboards/dashboards.yaml
      - source: nextjs-logs-dashboard
        target: /etc/grafana/provisioning/dashboards/nextjs-logs.json
    networks:
      - traefik-public
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.grafana.rule=Host(`monitor.tascrum.site`)"
        - "traefik.http.routers.grafana.entrypoints=websecure"
        - "traefik.http.routers.grafana.tls.certresolver=myresolver"
        - "traefik.http.routers.grafana-http.rule=Host(`monitor.tascrum.site`)"
        - "traefik.http.routers.grafana-http.entrypoints=web"
        - "traefik.http.routers.grafana-http.middlewares=grafana-https-redirect"
        - "traefik.http.middlewares.grafana-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"

  web-prod:
    image: ghcr.io/rstubryan/tascrum-web-prod:latest
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BASE_URL=http://api-tascrum.zeabur.app/api/v1
      - NEXT_PUBLIC_BASE_URL_BLOG=http://api-tascrum.zeabur.app/api/v1/blog
    networks:
      - traefik-public
    deploy:
      replicas: 2
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.web-prod.rule=Host(`tascrum.site`)"
        - "traefik.http.routers.web-prod.entrypoints=websecure"
        - "traefik.http.routers.web-prod.tls.certresolver=myresolver"
        - "traefik.http.routers.web-prod-http.rule=Host(`tascrum.site`)"
        - "traefik.http.routers.web-prod-http.entrypoints=web"
        - "traefik.http.routers.web-prod-http.middlewares=web-prod-https-redirect"
        - "traefik.http.middlewares.web-prod-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.services.web-prod.loadbalancer.server.port=3000"

  web-dev:
    image: ghcr.io/rstubryan/tascrum-web:latest
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_BASE_URL=http://api-tascrum.zeabur.app/api/v1
      - NEXT_PUBLIC_BASE_URL_BLOG=http://api-tascrum.zeabur.app/api/v1/blog
    networks:
      - traefik-public
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.web-dev.rule=Host(`dev.tascrum.site`)"
        - "traefik.http.routers.web-dev.entrypoints=websecure"
        - "traefik.http.routers.web-dev.tls.certresolver=myresolver"
        - "traefik.http.routers.web-dev-http.rule=Host(`dev.tascrum.site`)"
        - "traefik.http.routers.web-dev-http.entrypoints=web"
        - "traefik.http.routers.web-dev-http.middlewares=web-dev-https-redirect"
        - "traefik.http.middlewares.web-dev-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.services.web-dev.loadbalancer.server.port=3000"

configs:
  loki-config:
    content: |
      auth_enabled: false
      
      server:
        http_listen_port: 3100
        
      common:
        path_prefix: /loki
        storage:
          filesystem:
            chunks_directory: /loki/chunks
            rules_directory: /loki/rules
        replication_factor: 1
        ring:
          kvstore:
            store: inmemory
            
      schema_config:
        configs:
          - from: 2023-01-01
            store: tsdb
            object_store: filesystem
            schema: v12
            index:
              prefix: index_
              period: 24h

  promtail-config:
    content: |
      server:
        http_listen_port: 9080
        grpc_listen_port: 0
        
      positions:
        filename: /tmp/positions.yaml
        
      clients:
        - url: http://loki:3100/loki/api/v1/push
          
      scrape_configs:
        - job_name: containers
          docker_sd_configs:
            - host: unix:///var/run/docker.sock
              refresh_interval: 5s
          relabel_configs:
            - source_labels: ['__meta_docker_container_name']
              regex: '/(.*)'
              target_label: 'container'
            - source_labels: ['__meta_docker_container_label_com_docker_swarm_service_name']
              regex: '(.+)'
              target_label: 'service'
            - source_labels: ['__meta_docker_container_log_stream']
              target_label: 'logstream'
          pipeline_stages:
            - json:
                expressions:
                  level: level
                  message: message
                  timestamp: timestamp
            - labels:
                level:
            - timestamp:
                source: timestamp
                format: RFC3339Nano

  grafana-datasources:
    content: |
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          access: proxy
          url: http://loki:3100
          isDefault: true
          editable: true

  grafana-dashboards-config:
    content: |
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /etc/grafana/provisioning/dashboards

  nextjs-logs-dashboard:
    content: |
      {
        "annotations": {
          "list": [
            {
              "builtIn": 1,
              "datasource": {
                "type": "grafana",
                "uid": "-- Grafana --"
              },
              "enable": true,
              "hide": true,
              "iconColor": "rgba(0, 211, 255, 1)",
              "name": "Annotations & Alerts",
              "type": "dashboard"
            }
          ]
        },
        "editable": true,
        "fiscalYearStartMonth": 0,
        "graphTooltip": 0,
        "id": 1,
        "links": [],
        "liveNow": false,
        "panels": [
          {
            "datasource": {
              "type": "loki",
              "uid": "P8E80F9AEF21F6940"
            },
            "gridPos": {
              "h": 9,
              "w": 24,
              "x": 0,
              "y": 0
            },
            "id": 1,
            "options": {
              "dedupStrategy": "none",
              "enableLogDetails": true,
              "prettifyLogMessage": false,
              "showCommonLabels": false,
              "showLabels": false,
              "showTime": true,
              "sortOrder": "Descending",
              "wrapLogMessage": false
            },
            "pluginVersion": "10.0.3",
            "targets": [
              {
                "datasource": {
                  "type": "loki",
                  "uid": "P8E80F9AEF21F6940"
                },
                "editorMode": "builder",
                "expr": "{service=~\"tascrum_web.*\"}",
                "queryType": "range",
                "refId": "A"
              }
            ],
            "title": "Next.js Logs",
            "type": "logs"
          },
          {
            "datasource": {
              "type": "loki",
              "uid": "P8E80F9AEF21F6940"
            },
            "fieldConfig": {
              "defaults": {
                "color": {
                  "mode": "palette-classic"
                },
                "custom": {
                  "axisCenteredZero": false,
                  "axisColorMode": "text",
                  "axisLabel": "",
                  "axisPlacement": "auto",
                  "barAlignment": 0,
                  "drawStyle": "line",
                  "fillOpacity": 20,
                  "gradientMode": "none",
                  "hideFrom": {
                    "legend": false,
                    "tooltip": false,
                    "viz": false
                  },
                  "insertNulls": false,
                  "lineInterpolation": "smooth",
                  "lineWidth": 2,
                  "pointSize": 5,
                  "scaleDistribution": {
                    "type": "linear"
                  },
                  "showPoints": "never",
                  "spanNulls": false,
                  "stacking": {
                    "group": "A",
                    "mode": "none"
                  },
                  "thresholdsStyle": {
                    "mode": "off"
                  }
                },
                "mappings": [],
                "thresholds": {
                  "mode": "absolute",
                  "steps": [
                    {
                      "color": "green",
                      "value": null
                    },
                    {
                      "color": "red",
                      "value": 80
                    }
                  ]
                },
                "unit": "short"
              },
              "overrides": []
            },
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 0,
              "y": 9
            },
            "id": 2,
            "options": {
              "legend": {
                "calcs": [],
                "displayMode": "list",
                "placement": "bottom",
                "showLegend": true
              },
              "tooltip": {
                "mode": "single",
                "sort": "none"
              }
            },
            "pluginVersion": "10.0.3",
            "targets": [
              {
                "datasource": {
                  "type": "loki",
                  "uid": "P8E80F9AEF21F6940"
                },
                "editorMode": "builder",
                "expr": "rate({service=\"tascrum_web-prod\"}[$__interval])",
                "queryType": "range",
                "refId": "A"
              }
            ],
            "title": "Production Log Rate",
            "type": "timeseries"
          },
          {
            "datasource": {
              "type": "loki",
              "uid": "P8E80F9AEF21F6940"
            },
            "fieldConfig": {
              "defaults": {
                "color": {
                  "mode": "palette-classic"
                },
                "custom": {
                  "axisCenteredZero": false,
                  "axisColorMode": "text",
                  "axisLabel": "",
                  "axisPlacement": "auto",
                  "barAlignment": 0,
                  "drawStyle": "line",
                  "fillOpacity": 20,
                  "gradientMode": "none",
                  "hideFrom": {
                    "legend": false,
                    "tooltip": false,
                    "viz": false
                  },
                  "insertNulls": false,
                  "lineInterpolation": "smooth",
                  "lineWidth": 2,
                  "pointSize": 5,
                  "scaleDistribution": {
                    "type": "linear"
                  },
                  "showPoints": "never",
                  "spanNulls": false,
                  "stacking": {
                    "group": "A",
                    "mode": "none"
                  },
                  "thresholdsStyle": {
                    "mode": "off"
                  }
                },
                "mappings": [],
                "thresholds": {
                  "mode": "absolute",
                  "steps": [
                    {
                      "color": "green",
                      "value": null
                    },
                    {
                      "color": "red",
                      "value": 80
                    }
                  ]
                },
                "unit": "short"
              },
              "overrides": []
            },
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 12,
              "y": 9
            },
            "id": 3,
            "options": {
              "legend": {
                "calcs": [],
                "displayMode": "list",
                "placement": "bottom",
                "showLegend": true
              },
              "tooltip": {
                "mode": "single",
                "sort": "none"
              }
            },
            "pluginVersion": "10.0.3",
            "targets": [
              {
                "datasource": {
                  "type": "loki",
                  "uid": "P8E80F9AEF21F6940"
                },
                "editorMode": "builder",
                "expr": "rate({service=\"tascrum_web-dev\"}[$__interval])",
                "queryType": "range",
                "refId": "A"
              }
            ],
            "title": "Development Log Rate",
            "type": "timeseries"
          }
        ],
        "refresh": "10s",
        "schemaVersion": 38,
        "style": "dark",
        "tags": [],
        "templating": {
          "list": []
        },
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "timepicker": {},
        "timezone": "",
        "title": "Next.js Logs Dashboard",
        "version": 1,
        "weekStart": ""
      }

networks:
  traefik-public:
    driver: overlay
    attachable: true

volumes:
  traefik-certificates:
  grafana-data:
  loki-data:
  promtail-data: