name: Dummy CI Pipeline

on:
  push:
    branches:
      - dummy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --tag ghcr.io/rstubryan/tascrum-web-dummy:latest -f dummy.Dockerfile
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Push Docker image
        run: docker push ghcr.io/rstubryan/tascrum-web-dummy:latest
      - name: Logout from DockerHub
        run: docker logout

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DUMMY_SSH_HOST }}
          username: ${{ secrets.DUMMY_SSH_USER }}
          key: ${{ secrets.DUMMY_SSH_PRIVATE_KEY }}
          script: |
            docker pull ghcr.io/rstubryan/tascrum-web-dummy:latest
            docker stop tascrum-web-dummy || true
            docker rm tascrum-web-dummy || true
            docker run -d --name tascrum-web-dummy -p 3000:3000 --restart always ghcr.io/rstubryan/tascrum-web-dummy:latest