name: Dummy CI Pipeline

on:
  push:
    branches:
      - dummy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --tag ghcr.io/rstubryan/tascrum-web-dummy:latest -f dummy.Dockerfile
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Push Docker image
        run: docker push ghcr.io/rstubryan/tascrum-web-dummy:latest
      - name: Logout from DockerHub
        run: docker logout

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to VPS
        uses: cssnr/stack-deploy-action@v1
        with:
          name: tascrum-web-dummy
          file: compose-dummy.yaml
          host: ${{ secrets.PROD_SSH_HOST }}
          user: ${{ secrets.PROD_SSH_USER }}
          ssh_key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          registry_host: 'ghcr.io'
          registry_user: ${{ github.actor }}
          registry_pass: ${{ secrets.GHCR_PAT }}
          mode: compose
          args: '--force-recreate --remove-orphans'
          summary: true