name: Dummy CI Pipeline

on:
  push:
    branches:
      - dummy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build . --tag ghcr.io/rstubryan/tascrum-web-dummy:latest -f dummy.Dockerfile

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Push Docker image
        run: docker push ghcr.io/rstubryan/tascrum-web-dummy:latest

      - name: Logout from GitHub Container Registry
        run: docker logout

      - name: Copy compose-dummy.yaml and haproxy.cfg to VPS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USER }}
          key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          source: "compose-dummy.yaml,haproxy.cfg"
          target: "/home/${{ secrets.PROD_SSH_USER }}/tascrum-web-dummy"

      - name: Login registry and deploy on VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USER }}
          key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          script: |
            echo '${{ secrets.GHCR_PAT }}' | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/rstubryan/tascrum-web-dummy:latest
            docker compose -f ~/compose-dummy.yaml -p tascrum-web-dummy up -d --force-recreate --remove-orphans